definitions:
  controller.UserLogin:
    properties:
      account:
        example: account
        type: string
      password:
        example: password
        type: string
    required:
    - account
    - password
    type: object
  controller.UserRegister:
    properties:
      account:
        example: account
        type: string
      email:
        example: test123@gmail.com
        type: string
      password:
        example: password
        type: string
    required:
    - account
    - email
    - password
    type: object
host: localhost:3000
info:
  contact: {}
  description: Gin swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin swagger
  version: "1.0"
paths:
  /v1/users:
    post:
      parameters:
      - description: language
        in: header
        name: language
        required: true
        type: string
      - description: register
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/controller.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - user
  /v1/users/{id}:
    get:
      parameters:
      - default: 1
        description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      tags:
      - user
  /v1/users/login:
    post:
      parameters:
      - description: login
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/controller.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - user
  /vote/{id}:
    get:
      consumes:
      - application/json
      description: 根據提供的 ID 檢查投票是否存在
      parameters:
      - description: 投票ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 根據提供的 ID 檢查投票是否存在
      tags:
      - 投票
  /vote/all:
    get:
      consumes:
      - application/json
      description: 檢索所有投票
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 檢索所有投票
      tags:
      - 投票
  /vote/create:
    post:
      consumes:
      - application/json
      description: 創建一個新的投票
      parameters:
      - description: 投票標題
        in: query
        name: title
        required: true
        type: string
      - description: 投票描述
        in: query
        name: description
        required: true
        type: string
      - description: 開始時間
        in: query
        name: startTime
        required: true
        type: string
      - description: 結束時間
        in: query
        name: endTime
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 創建一個新的投票
      tags:
      - 投票
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
